train:
  id: csgo
  size: [150, 280]
num_actions: 51
path_data_low_res: G:\マイドライブ\world_model\final\03_Diffusion-Models-and-World-Models\src\data\csgo_processed\low_res # TO DEFINE
path_data_full_res: G:\マイドライブ\world_model\final\03_Diffusion-Models-and-World-Models\src\data\csgo_processed\full_res # TO DEFINE
keymap: csgo
