_target_: agent.AgentConfig

denoiser:
  _target_: models.diffusion.DenoiserConfig
  sigma_data: 0.5
  sigma_offset_noise: 0.1
  noise_previous_obs: true
  upsampling_factor: null
  inner_model:
    _target_: models.diffusion.InnerModelConfig
    img_channels: 3
    num_steps_conditioning: 4
    cond_channels: 512
    depths:
    - 2
    - 2
    - 2
    - 2
    channels:
    - 64
    - 128
    - 256
    - 512
    attn_depths:
    - 0
    - 0
    - 1
    - 1

upsampler: null

rew_end_model:
  _target_: models.rew_end_model.RewEndModelConfig
  lstm_dim: 512
  img_channels: 3
  img_size: ${env.train.size}
  cond_channels: 512
  depths:
  - 2
  - 2
  - 2
  channels:
  - 64
  - 128
  - 256
  attn_depths:
  - 0
  - 0
  - 1

actor_critic:
  _target_: models.actor_critic.ActorCriticConfig
  lstm_dim: 512
  img_channels: 3
  img_size: ${env.train.size}
  channels:
  - 32
  - 64
  - 128
  down:
  - 1
  - 1
  - 1
